# Generated by Django 2.2.26 on 2022-04-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220403_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comhabW',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
